api_platform:
    title: 'API Lasazao'
    description: 'API pour le projet Lasazao'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
        swagger_ui_extra_configuration:
            persistAuthorization: true
            displayOperationId: true
            displayRequestDuration: true
            filter: true
            operationsSorter: method
            tagsSorter: alpha
            docExpansion: none
            tryItOutEnabled: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
